#! /usr/bin/python
import sys
sys.path.insert(0, './libary/')

from getInputs import startInputScanner, readMinMax, readInputs # local file # TODO
from log import createLogfile, log # local file
from setSpeed import setSpeed # local file
from setSteer import setSteer # local file
from PIDloop import PIDloop # local file
from alert import alert # local file
import time

def main():
	PIDs = [1, 1, 1]
	PIDresult = 0
	startInputScanner()
	readMinMax()

	time.sleep(3)

	print("")
	print("")
	print("")
	print("")
	print("")

	try:
		while True:
			Axis = []
			Axis = readInputs()
			try:
				BAR_LEN = 15

				for i in range(Axis)
					ACTIVE_BAR = (Axis[i] - 1000) * (BAR_LEN / 100)
					INACTIVE_BAR = BAR_LEN - ACTIVE_BAR
					print("\033[A")
					print(f"Channel{i + 1}:  {Axis[i]:04} | [{ACTIVE_BAR}{INACTIVE_BAR}]")
			except:
				print("ERROR")

	#		#if accelerometer is available
	#		PIDresult = PIDloop(PIDs)

			time.sleep(0.04)
	except KeyboardInterrupt:
		sys.exit()

main()
